### ISSUE TITLE
Unable to run nightwatch tests cases against local server

### ISSUE THREAD

**Issue by KingMackle** [371team4/371Team4#18]
Nightwatch tests that are being executed against local server are failing 100% of the time 

## Description

Nightwatch test cases running against a local server instance, are configured with incorrect address URL, therefore causing all the tests to fail.  

## Expected Behavior

Nightwatch tests should be runnable against local server 

## Actual Behavior

Nightwatch tests are not running against local server instance 

## Possible Fix

need to remove a space from the server url and add add a condition to allow for host name to be set on node process

## Steps to Reproduce

1. On the command line where a clone of the repo exists, run the command `npm run e2e`
2. You will see the first test case named 'test title' has failed and mentions that the error for failure was incorrect WebPage title name. However, when you observe the browser you will see that it doesn't go to any address. 

## Context

As a Developer/Jenkins, I need to be able to run test case against local server 

## Console log

```
D:\Program Files\Jenkins\workspace\371team4_PR-17-S5C5SSM5LFH7VFPRPCX5GZ42NKH7UXATWWSRTWCZ6NE3OXJKVOVA>npm run e2e 

> retirement-party@0.0.3 e2e D:\Program Files\Jenkins\workspace\371team4_PR-17-S5C5SSM5LFH7VFPRPCX5GZ42NKH7UXATWWSRTWCZ6NE3OXJKVOVA

> node test/e2e/runner.js
Compiling dev server...
Compiling dev server COMPLETED
Starting selenium server... started - PID:  4816
[Test] Test Suite
=====================
Running:  test title
 âˆš Element <body> was visible after 29 milliseconds.
 Ã— Testing if the page title equals "Retirement Party".  - expected "Retirement Party" but got: ""
    at Object.testTitle [as test title] (D:/Program Files/Jenkins/workspace/371team4_PR-17-S5C5SSM5LFH7VFPRPCX5GZ42NKH7UXATWWSRTWCZ6NE3OXJKVOVA/test/e2e/specs/test.js:18:15)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
FAILED:  1 assertions failed and 1 passed (4.07s)
[Web App] Test Suite
========================
Running:  Demo WebbApp test
 âˆš Element <body> was visible after 32 milliseconds.
 âˆš Element <#app > div.application--wrap > div > main > div.container.fluid.fill-height > div > div > div > div > div > div.card__actions > button > div> was visible after 29 milliseconds.
 âˆš Element <#app > div.application--wrap > div > main > div.container.fluid.fill-height > div > div > div.container > div > div > div > nav > div > button.btn.btn--round.theme--dark.pink > div> was visible after 57 milliseconds.
 âˆš Element <#app > div.application--wrap > nav > div > button.toolbar__side-icon.btn.btn--icon > div> was visible after 56 milliseconds.
 âˆš Element <#app > div.application--wrap > aside > ul > li:nth-child(4) > a > div.list__tile__content > div> was visible after 541 milliseconds.

OK. 5 assertions passed. (19.919s)
 _________________________________________________
 TEST FAILURE:  1 assertions failed, 6 passed. (24.574s)
 Ã— test
   - test title (4.07s)
   Testing if the page title equals "Retirement Party".  - expected "Retirement Party" but got: ""
       at Object.testTitle [as test title] (D:/Program Files/Jenkins/workspace/371team4_PR-17-S5C5SSM5LFH7VFPRPCX5GZ42NKH7UXATWWSRTWCZ6NE3OXJKVOVA/test/e2e/specs/test.js:18:15)
       at _combinedTickCallback (internal/process/next_tick.js:131:7)

   SKIPPED:
   - test header
   - test menu
   - test showview
   - test card count
   - test text field

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! retirement-party@0.0.3 e2e: `node test/e2e/runner.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the retirement-party@0.0.3 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\npm-cache\_logs\2018-02-16T03_56_27_937Z-debug.log
script returned exit code 1
```

## Your Environment

* Version used: Node 8.9
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Windows 7

**Comment by KingMackle** [comment]
Resoved in [#30](https://github.com/371team4/371Team4/pull/30)
